### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by nebasam** [nebasam/Industry---Casualty-Challenge#3]
**Task 1**
- [x] Conduct an exploratory data analysis on the data & communicate useful insights. Ensure that you identify and treat all missing values and outliers in the dataset by using appropriate methods.
- [x] Perform feature extraction and scaling 
**Task 2**
- [x] Split data into training and hold-out set
- [x] Create a causal graph using all training data and get the insights (this will be considered the ground truth)
- [x] Create new causal graphs using increasing fractions of the data and compare with the ground truth graph. The comparison can be done with a Jaccard Similarity Index, measuring the intersection and union of the graph edges
- [x] After reaching a stable causal graph, select only variables that point directly to the target variable
- [x] Train one model using all variables and another using only the variables selected by the graph
- [x] Measure how much each of the models overfit the hold-out set created in step 1.
